(define (problem building-scenario)
  (:domain smart-building)
  (:init
    (dark)
    (motion-detected)
    (sound-detected)
    (led-off)
    (plugwise-off)
  )
  (:goal (and (led-on) (plugwise-on)))
)
